export const colors = {
  White: true,
  Blue: true,
  Black: true,
  Red: true,
  Green: true,
  Colorless: true
}

export const mainCard = {
  artist: 'Jaime Jones',
  cmc: 4,
  colorIdentity: ['W'],
  colors: ['White'],
  flavor: '"The darkness crawls with vampires and ghouls, but we are not without allies."\n—Mikaeus, the Lunarch',
  id: '1db688d574646fcdee55fcd2839149299d084b0b',
  imageName: 'abbey griffin',
  layout: 'normal',
  manaCost: '{3}{W}',
  mciNumber: '1',
  multiverseid: 235595,
  name: 'Abbey Griffin',
  number: '1',
  power: '2',
  rarity: 'Common',
  subtypes: ['Griffin'],
  text: 'Flying, vigilance',
  toughness: '2',
  type: 'Creature — Griffin',
  types: ['Creature'],
  setCode: 'isd',
  variants: [
    {
      artist: 'Jaime Jones',
      cmc: 4,
      colorIdentity: ['W'],
      colors: ['White'],
      flavor: '"The darkness crawls with vampires and ghouls, but we are not without allies."\n—Mikaeus, the Lunarch',
      id: '1db688d574646fcdee55fcd2839149299d084b0b',
      imageName: 'abbey griffin',
      layout: 'normal',
      manaCost: '{3}{W}',
      mciNumber: '1',
      multiverseid: 235595,
      name: 'Abbey Griffin',
      number: '1',
      power: '2',
      rarity: 'Common',
      subtypes: ['Griffin'],
      text: 'Flying, vigilance',
      toughness: '2',
      type: 'Creature — Griffin',
      types: ['Creature'],
      setCode: 'isd',
      image: 'http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=235595',
      setIcon: 'ss ss-isd ss-common',
      cardUrl: 'abbey-griffin'
    }
  ],
  image: 'http://gatherer.wizards.com/Handlers/Image.ashx?type=card&multiverseid=235595',
  setIcon: 'ss ss-isd ss-common',
  cardUrl: 'abbey-griffin'
}
